### ISSUE TITLE
Loading of the schema has failed

### ISSUE THREAD

**Issue by blim8183** [juliogarciag/rails-atom-schema#1]
I'm getting the error `Loading of the schema has failed` when I open the panel in my projects. I'm using version 1.22.0 of Atom on a Mac. I've tried it in multiple projects.

Let me know if there's any other information about my environment that might be helpful!

**Comment by juliogarciag** [comment]
Yes, just two things:

1. What the atom console says? (it opens just like a chrome console)
2. What's the error resulting of running this command from the project root?

    ```sh
    bin/rails runner ~/.atom/packages/rails-atom-schema/lib/ruby-scripts/fetch_schema.rb
    ```

The last command is the way the package gets the needed Rails information, so if it doesn't run, it says that message.

**Comment by blim8183** [comment]
I don't see anything of note in the console.

Here's the output of that command:

```
{
  "modelSchemas": {
    "/Users/blim/workspace/fino/app/models/api_key.rb": {
      "tableName": "api_keys",
      "modelName": "ApiKey",
      "modelPath": "/Users/blim/workspace/fino/app/models/api_key.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "description",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "token",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/assertion_result.rb": {
      "tableName": "assertion_results",
      "modelName": "AssertionResult",
      "modelPath": "/Users/blim/workspace/fino/app/models/assertion_result.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "result",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "build_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "step_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "notes",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "test_environment_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "position",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "test_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "pending_notes",
          "type": "boolean",
          "default": "false",
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/attachment.rb": {
      "tableName": "attachments",
      "modelName": "Attachment",
      "modelPath": "/Users/blim/workspace/fino/app/models/attachment.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "filepicker_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "filepicker_filename",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "filepicker_mimetype",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "filepicker_size",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "owner_type",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "owner_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "reference_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/build.rb": {
      "tableName": "builds",
      "modelName": "Build",
      "modelPath": "/Users/blim/workspace/fino/app/models/build.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "status",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "pull_request_number",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "head_sha",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "user_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "deployment_status_payload",
          "type": "json",
          "default": "{}",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "start_time",
          "type": "datetime",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "end_time",
          "type": "datetime",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "pull_request_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "json_snapshot",
          "type": "jsonb",
          "default": "\"{}\"",
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/build_issue.rb": {
      "tableName": "build_issues",
      "modelName": "BuildIssue",
      "modelPath": "/Users/blim/workspace/fino/app/models/build_issue.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "build_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "issue_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/issue.rb": {
      "tableName": "issues",
      "modelName": "Issue",
      "modelPath": "/Users/blim/workspace/fino/app/models/issue.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "ignored",
          "type": "boolean",
          "default": "false",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "source_internal_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "source_public_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "title",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "body",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "labels",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "milestone",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "comments_count",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "source_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "pending_builds_count",
          "type": "integer",
          "default": "0",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "tests_count",
          "type": "integer",
          "default": "0",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "source_name",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/test.rb": {
      "tableName": "tests",
      "modelName": "Test",
      "modelPath": "/Users/blim/workspace/fino/app/models/test.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "issue_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "body",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "title",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "precondition",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "position",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/membership.rb": {
      "tableName": "memberships",
      "modelName": "Membership",
      "modelPath": "/Users/blim/workspace/fino/app/models/membership.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "user_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/pull_request.rb": {
      "tableName": "pull_requests",
      "modelName": "PullRequest",
      "modelPath": "/Users/blim/workspace/fino/app/models/pull_request.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_issue_number",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "title",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "body",
          "type": "text",
          "default": "",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "deployment_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/repo.rb": {
      "tableName": "repos",
      "modelName": "Repo",
      "modelPath": "/Users/blim/workspace/fino/app/models/repo.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "full_name",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "pending_builds_count",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "owner_avatar_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "issues_without_tests_count",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_test_environments_count",
          "type": "integer",
          "default": "0",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "active",
          "type": "boolean",
          "default": "true",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/repo_test_environment.rb": {
      "tableName": "repo_test_environments",
      "modelName": "RepoTestEnvironment",
      "modelPath": "/Users/blim/workspace/fino/app/models/repo_test_environment.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "test_environment_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/step.rb": {
      "tableName": "steps",
      "modelName": "Step",
      "modelPath": "/Users/blim/workspace/fino/app/models/step.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "test_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "action",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "assertion",
          "type": "text",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "position",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/test_environment.rb": {
      "tableName": "test_environments",
      "modelName": "TestEnvironment",
      "modelPath": "/Users/blim/workspace/fino/app/models/test_environment.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "platform",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "operating_system",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "operating_system_version",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "device",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "browser",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "browser_version",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "screen_orientation",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "viewport_width",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "position",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/user.rb": {
      "tableName": "users",
      "modelName": "User",
      "modelPath": "/Users/blim/workspace/fino/app/models/user.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_access_token",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_uid",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "name",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "avatar_url",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "github_login",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    },
    "/Users/blim/workspace/fino/app/models/webhook.rb": {
      "tableName": "webhooks",
      "modelName": "Webhook",
      "modelPath": "/Users/blim/workspace/fino/app/models/webhook.rb",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "raw_data",
          "type": "json",
          "default": "{}",
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "repo_id",
          "type": "integer",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "provider",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "event",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "webhook_id",
          "type": "string",
          "default": null,
          "allowsNull": true,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "created_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "default": null,
          "allowsNull": false,
          "limit": null,
          "precision": null,
          "scale": null
        }
      ]
    }
  },
  "version": 20170629132729
}
```

**Comment by juliogarciag** [comment]
I found a possible problem (but cannot be sure because I don't have the same configuration). The ruby script that gets the schema is indeed working, as you posted, and the only thing I could replicate was the fact that the command didn't actually ended. After digging a bit I noticed that the first time spring processes are called (which are created by `bin/rails runner`) they don't call any side of the promise of node's `child_process.exec`, leaving the state as `failed`. Somehow, lowering the level of the code to attach callbacks into the stdout and stderr strams worked well for me.

Can you update the package and try again? I also added an option to reload the schema when it fails  just in case the first time the command doesn't notify node about its ouput.

**Comment by blim8183** [comment]
I'm still getting the same result. I've tried using the reload schema option you added too but it's not working.

<img width="1439" alt="screen shot 2017-11-13 at 9 35 11 pm" src="https://user-images.githubusercontent.com/4014/32760078-9601f5a6-c8ba-11e7-8b65-aa659fdc4136.png">

**Comment by juliogarciag** [comment]
What this means is that it was a different issue than the one I solved. Interestingly, running in dev mode gives the option to see what redux dispatched. `SCHEMA_FAILED` was dispatched so it would be nice to also see what was the action payload was. (It's the same screenshot but scrolling down a bit further)

Also, I also added an additional log in the last commit that logs the stdout, stderr, exit code and the signal by which the ruby process was killed (in th case it was killed): https://github.com/juliogarciag/rails-atom-schema/commit/576b618a1df6b7f28fe41f855d82e3d6a00f05e6. I released a new patch version with that log. I think that should contain enough information to know what happened.

**Comment by blim8183** [comment]
Looks like it's something weird with my Atom configuration. My app's Gemfile is specifying Ruby 2.3.3 but Atom is using 2.4.1. I think this is because I had Rubocop misconfigured to use 2.4.1 but I tried disabling all my other packages and Atom continued to insist on using 2.4.1. My second thought was that maybe Atom was using my system Ruby (I'm using RVM) but my system Ruby is 2.0.0.

¯\_(ツ)_/¯

Anyway, when I updated my Gemfile to use 2.4.1 your plugin worked.

```
`"/Users/blim/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/definition.rb:487:in `validate_ruby!': Your Ruby version is 2.4.1, but your Gemfile specified 2.3.3 (Bundler::RubyVersionMismatch)
from /Users/blim/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/definition.rb:462:in `validate_runtime!'
from /Users/blim/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler.rb:101:in `setup'
from /Users/blim/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/setup.rb:20:in `<top (required)>'
from /Users/blim/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/blim/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/blim/workspace/fino/config/boot.rb:3:in `<top (required)>'
from bin/rails:8:in `require_relative'
from bin/rails:8:in `<main>'
```

**Comment by juliogarciag** [comment]
Wow... that was weird. I think it should have something to do with the way RVM recognizes the version inside the Gemfile or the way it's activated. Internally, what I'm doing here is just a regular `spawn("bin/rails"...` so maybe it just used the default RVM version.

**Comment by blim8183** [comment]
lol, I uninstalled 2.4.1 and now it's trying to use my system ruby 😭

**Comment by juliogarciag** [comment]
I thought `bin/rails` was a kind of independent/standalone way to execute the rails command of a given project regardless of where the command was executed... Maybe in the case of `rvm` I would need to explore how to activate the given rails command. I'm thinking of first having an atom setting for `Rails executable` which defaults to `bin/rails` but can be tweaked for RVM.

**Comment by vanboom** [comment]
I am having this same issue, however, developer tools shows that it is trying to use ruby 1.8.  I have a clean install of Ubuntu 18.04 with rbenv set to use ruby 2.3.1.   I have never had ruby 1.8 installed on this system.  Thanks for any suggestions on where to hunt this down.  Seems like this would be a great capability to have in Atom. 

````
{code: 127, reason: null, stdout: "", stderr: "/usr/bin/env: ‘ruby1.8’: No such file or directory↵"}
code
:
127
reason
:
null
stderr
:
"/usr/bin/env: ‘ruby1.8’: No such file or directory↵"
stdout
:
""
__proto__
:
Object
````

**Comment by vanboom** [comment]
Update: ruby 1.8 was in my `script/rails `  I have corrected that and now seeing a different error message...
````
/home/doug/.atom/packages/rails-atom-schema/lib/ruby-scripts/fetch_schema.rb:44:in `block in serialize_model_columns': undefined method `sql_type_metadata' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x005610a9570c78> (NoMethodError)
````

My rails app does use the Postgres array column type.  I will try to debug further and offer a PR if I can get a fix.

**Comment by vanboom** [comment]
fetch_schema.rb is using `sql_type_metadata` which is a MySQL specific method.  This code needs to be modified to fallback gracefully if the MySQL methods are not supported.  I have done this below using **try**.  Not experienced at issuing PR for Atom projects, but I will try.

```ruby
    sort_columns(model_class.columns).map do |column|
      {
        name: column.name,
        type: column.type,
        default: column.default,
        allowsNull: column.null,
        limit: column.try(:sql_type_metadata).try(:limit) || column.try(:limit),
        precision: column.try(:sql_type_metadata).try(:precision) || column.try(:precision),
        scale: column.try(:sql_type_metadata).try(:scale) || column.try(:scale)
      }
    end
  end
```

**Comment by vanboom** [comment]
the old gem rails-model-schema displays the schema just fine

**Comment by grassiricardo** [comment]
Hello
For me is this erros
`Uncaught (in promise) Error: ENOENT: no such file or directory, lstat '/Users/ricardograssi/Projects/teste/db/schema.rb'`

**Comment by vanboom** [comment]
Check my PR #6, if you are using PostgreSQL, this plugin has MySQL specific code in it which I was able to refactor.
